LOG_PATH = 'logs/logs.txt'
LANE_CREEPS_SPAWN_FREQUENCY_IN_SECONDS = 30
FORREST_CREEPS_SPAWN_FREQUENCY_IN_SECONDS = 60
RUNE_SPAWN_FREQUENCY_IN_SECONDS = 120
EXPERIENCE_RUNE_SPAWN_FREQUENCY_IN_SECONDS = 420
STACK_FORREST_CREEPS_AT = 56
